<?php
/**
 * Created by PhpStorm.
 * User: Windows
 * Date: 2018/11/7
 * Time: 13:59
 */

require_once './Decorator.php';

class HighScoreDecorator extends Decorator
{
    public function __construct(SchoolReport $sr)
    {
        parent::__construct($sr);
    }

    private function reportHighScore()
    {
        echo '这次语文考试最高分是75分，数学是80，自然是50' . PHP_EOL;
    }

    public function report()
    {
        $this->reportHighScore();
        parent::report(); // TODO: Change the autogenerated stub
    }
}