<?php
/**
 * Created by PhpStorm.
 * User: Windows
 * Date: 2018/11/7
 * Time: 13:46
 */

require_once './FourGradeSchoolReport.php';

class SugarFourGradeSchoolReport extends FourGradeSchoolReport
{
    //定义一个美化的方法
    private function reportHighSchool()
    {
        echo '这次语文考试最高分是75分，数学是80，自然是50' . PHP_EOL;
    }

    private function reportSort()
    {
        echo '我的排名是10'  . PHP_EOL;
    }

    public function report()
    {
        $this->reportHighSchool();
        parent::report(); // TODO: Change the autogenerated stub
        $this->reportSort();
    }

}